//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minesweeper.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minesweeper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   クリアおめでとう！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearTextLableContext {
            get {
                return ResourceManager.GetString("ClearTextLableContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hh\:mm\:ss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearTimeFormat {
            get {
                return ResourceManager.GetString("ClearTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリアタイム　：　 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearTimeLabelContext {
            get {
                return ResourceManager.GetString("ClearTimeLabelContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseButtonContext {
            get {
                return ResourceManager.GetString("CloseButtonContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あぼん に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GameOverTextLabelContext {
            get {
                return ResourceManager.GetString("GameOverTextLabelContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戦績 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GameResultWindowTitle {
            get {
                return ResourceManager.GetString("GameResultWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   難易度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenubarHeaderGameLevel {
            get {
                return ResourceManager.GetString("MenubarHeaderGameLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenubarHeaderOption {
            get {
                return ResourceManager.GetString("MenubarHeaderOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenubarItemCloseWindow {
            get {
                return ResourceManager.GetString("MenubarItemCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初級 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenubarItemGameLevelEasy {
            get {
                return ResourceManager.GetString("MenubarItemGameLevelEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上級 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenubarItemGameLevelHard {
            get {
                return ResourceManager.GetString("MenubarItemGameLevelHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中級 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenubarItemGameLevelNormal {
            get {
                return ResourceManager.GetString("MenubarItemGameLevelNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戦績 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenubarItemGameResults {
            get {
                return ResourceManager.GetString("MenubarItemGameResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ● に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MineCellMark {
            get {
                return ResourceManager.GetString("MineCellMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   × に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MineClickedMark {
            get {
                return ResourceManager.GetString("MineClickedMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ○ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MineRightClickMark {
            get {
                return ResourceManager.GetString("MineRightClickMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuestionMarked {
            get {
                return ResourceManager.GetString("QuestionMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り爆弾数　：　 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemainMineCountLabel {
            get {
                return ResourceManager.GetString("RemainMineCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResetButtonContext {
            get {
                return ResourceManager.GetString("ResetButtonContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartButtonContext {
            get {
                return ResourceManager.GetString("StartButtonContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   俺のマインスイーパー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
