//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJack.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackJack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   掛け金 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BetCoins {
            get {
                return ResourceManager.GetString("BetCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   掛け金を入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BetCoinsInputDialogView_MainMessage {
            get {
                return ResourceManager.GetString("BetCoinsInputDialogView_MainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   掛け金入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BetCoinsInputDialogView_WindowTitle {
            get {
                return ResourceManager.GetString("BetCoinsInputDialogView_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダブル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonContent_Double {
            get {
                return ResourceManager.GetString("ButtonContent_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヒット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonContent_Hit {
            get {
                return ResourceManager.GetString("ButtonContent_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インシュランス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonContent_Insurance {
            get {
                return ResourceManager.GetString("ButtonContent_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スプリット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonContent_Split {
            get {
                return ResourceManager.GetString("ButtonContent_Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonContent_Stand {
            get {
                return ResourceManager.GetString("ButtonContent_Stand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所持金 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrentCoins {
            get {
                return ResourceManager.GetString("CurrentCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディーラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DealerName {
            get {
                return ResourceManager.GetString("DealerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   勝利時獲得金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetCoinsWhenYouWin {
            get {
                return ResourceManager.GetString("GetCoinsWhenYouWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラックジャック！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_BlackJack {
            get {
                return ResourceManager.GetString("Message_BlackJack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バースト！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Burst {
            get {
                return ResourceManager.GetString("Message_Burst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダブルできます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Double {
            get {
                return ResourceManager.GetString("Message_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ああ？金がたりねえじゃねえか？！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Gameover_Dealer {
            get {
                return ResourceManager.GetString("Message_Gameover_Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   健は首をはねられた！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Gameover_Player {
            get {
                return ResourceManager.GetString("Message_Gameover_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インシュランスできます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Insurance {
            get {
                return ResourceManager.GetString("Message_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インシュランスが支払われました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_InsurancePayed {
            get {
                return ResourceManager.GetString("Message_InsurancePayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スプリットできます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Split {
            get {
                return ResourceManager.GetString("Message_Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   健 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   俺のブラックジャック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
